{% set min_go = ">=1.22" %}
{% set min_go = ">=1.22" %}
{% set name = "kubo" %}
{% set version = "0.31.0" %}
{% set gomodule = "github.com/ipfs/" ~ name %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - folder: src/{{ gomodule }}
    url: https://{{ gomodule }}/releases/download/v{{ version }}/{{ name }}-source.tar.gz
    sha256: 6e4f44e8ae5e388a0f51115a5a7c178b2521a99c56ea4fe99a91af4e0acce108

build:
  number: 0

requirements:
  # from e.g. https://github.com/ipfs/kubo/blob/v0.28.0/go.mod#L253
  {% set min_go = ">=1.22" %}
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - go {{ min_go }}  # [unix]
    - go-cgo {{ min_go }}  # [unix]
    - {{ compiler('go') }}  # [win]
    - posix  # [win]
    - go-licenses
    - make  # [unix]
  host:
    - openssl  # [unix]
  run_constrained:
    - go-ipfs >=9000

{% set cid = "/ipfs/Qmc5gCcjYypU7y28oCALwfSvxCBskLuPKWpK4qpterKC7z" %}
{% set ipfs_args = "--debug" %}

test:
  commands:
    - ipfs --version
    - ipfs --help
    - ipfs commands
    - ipfs {{ ipfs_args }} init
    # no longer appear to work in CI
    # - ipfs {{ ipfs_args }} ls {{ cid }}
    # - ipfs {{ ipfs_args }} refs {{ cid }}
    # - ipfs {{ ipfs_args }} get {{ cid }}
    # - ipfs {{ ipfs_args }} cat {{ cid }}
    - echo "hello conda-forge" > hello.txt
    - ipfs {{ ipfs_args }} add hello.txt

about:
  home: https://ipfs.tech
  license: Apache-2.0 or MIT
  license_file:
    # directly provided by upstream
    - src/{{ gomodule }}/LICENSE-APACHE
    - src/{{ gomodule }}/LICENSE-MIT
    - library_licenses/
    - go-licenses.log

  summary: IPFS implementation in Go

  description: |
    Kubo (go-ipfs) the earliest and most widely used implementation of IPFS.

    It includes:
      - an IPFS daemon server
      - extensive command line tooling
      - an HTTP Gateway (/ipfs/, /ipns/) for serving content to HTTP browsers
      - an HTTP RPC API (/api/v0) for controlling the daemon node

  doc_url: https://docs.ipfs.tech
  dev_url: https://{{ gomodule }}

extra:
  recipe-maintainers:
    - bollwyvl
